#!/bin/bash
set -euo pipefail

# Generate notes/handoffs/INDEX.md by scanning all notes/*/handoffs/**/*.md
#
# Usage:
#   generate-handoff-index.sh [ROOT_DIR]
#
# ROOT_DIR defaults to git toplevel. Pass a worktree path when called
# from push-logs.sh.

ROOT_DIR="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
NOTES_DIR="$ROOT_DIR/notes"
INDEX_FILE="$NOTES_DIR/handoffs/INDEX.md"

if [[ ! -d "$NOTES_DIR" ]]; then
  echo "generate-handoff-index: no notes/ directory found in $ROOT_DIR" >&2
  exit 0
fi

mkdir -p "$(dirname "$INDEX_FILE")"

# --- Collect handoff metadata ---
# Format per line: user|status|created|title|relpath
ENTRIES=()

while IFS= read -r -d '' file; do
  # Skip non-handoff files
  basename="$(basename "$file")"
  case "$basename" in
    INDEX.md|README.md|.gitkeep) continue ;;
  esac

  # Extract user from path: notes/<user>/handoffs/...
  relpath="${file#"$NOTES_DIR/"}"
  user="${relpath%%/*}"

  # Determine status from directory structure
  # Files in completed/ → completed; files directly in handoffs/ → active
  case "$relpath" in
    */completed/*) status="completed" ;;
    */active/*)    status="active" ;;
    *)
      # Fallback: parse **Status**: line from file content
      status_line="$(grep -m1 -oP '^\*\*Status\*\*:\s*\K.+' "$file" 2>/dev/null || true)"
      if [[ -n "$status_line" ]]; then
        status_lower="$(echo "$status_line" | tr '[:upper:]' '[:lower:]' | xargs)"
        case "$status_lower" in
          completed|complete|done) status="completed" ;;
          blocked)                 status="blocked" ;;
          *)                       status="active" ;;
        esac
      else
        status="active"
      fi
      ;;
  esac

  # Extract title: first H1 heading
  title="$(grep -m1 -oP '^#\s+\K.+' "$file" 2>/dev/null || echo "$basename")"

  # Extract created date: **Created**: YYYY-MM-DD
  created="$(grep -m1 -oP '^\*\*Created\*\*:\s*\K[0-9]{4}-[0-9]{2}-[0-9]{2}' "$file" 2>/dev/null || true)"
  if [[ -z "$created" ]]; then
    # Fallback to file modification date
    created="$(date -r "$file" +%Y-%m-%d 2>/dev/null || stat -c %y "$file" 2>/dev/null | cut -d' ' -f1 || echo "unknown")"
  fi

  # Relative link from notes/handoffs/INDEX.md to the file
  linkpath="../$relpath"

  ENTRIES+=("${user}|${status}|${created}|${title}|${linkpath}")
done < <(find "$NOTES_DIR" -path "*/handoffs/*.md" -print0 2>/dev/null | sort -z)

# --- Group entries by user, then status ---

# Get sorted unique users
USERS=()
for entry in "${ENTRIES[@]}"; do
  USERS+=("${entry%%|*}")
done
# Deduplicate and sort
mapfile -t USERS < <(printf '%s\n' "${USERS[@]}" | sort -u)

# --- Write INDEX.md ---
{
  echo "# Handoff Index"
  echo ""
  echo "> Auto-generated by scanning all notes/*/handoffs/*.md. Do not edit manually."
  echo "> Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

  for user in "${USERS[@]}"; do
    echo ""
    echo "## $user"

    # Collect entries for this user, grouped by status
    for status_group in active blocked completed; do
      group_lines=()
      for entry in "${ENTRIES[@]}"; do
        IFS='|' read -r e_user e_status e_created e_title e_link <<< "$entry"
        if [[ "$e_user" == "$user" && "$e_status" == "$status_group" ]]; then
          group_lines+=("- [${e_title}](${e_link}) — ${e_created}")
        fi
      done

      if [[ ${#group_lines[@]} -gt 0 ]]; then
        # Capitalize status group header
        header="$(echo "${status_group:0:1}" | tr '[:lower:]' '[:upper:]')${status_group:1}"
        echo ""
        echo "### $header"
        echo ""
        for line in "${group_lines[@]}"; do
          echo "$line"
        done
      fi
    done
  done
} > "$INDEX_FILE"

echo "generate-handoff-index: wrote $INDEX_FILE (${#ENTRIES[@]} entries, ${#USERS[@]} users)"
